name: Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build
      - name: Get version
        id: package_version
        run: echo "::set-output name=VERSION::$(node -p "require('./package.json').version")"
      - name: Bump version and push tag
        id: create_new_tag
        uses: actions-ecosystem/action-bump-semver@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          current_version: ${{ steps.package_version.outputs.VERSION }}
          tag_prefix: 'v'
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
